### ISSUE TITLE
Interested in Merging this Provisioner to Core?

### ISSUE THREAD

**Issue by stack72** [jonmorehouse/terraform-provisioner-ansible#29]
Hi @jonmorehouse 

I just got made aware of this project - nice work! Would you be interested in getting this provisioner into the terraform core project? 

Paul

**Comment by lucazz** [comment]
Hi @stack72, 

I'd like to volunteer here if @jonmorehouse doesn't feel interested in doing so.
(Assuming, of course @jonmorehouse agrees to other people maintaining this code.)

**Comment by stack72** [comment]
Hi @lucazz 

thanks so much for getting back to me on this - I wish I could push forward with this agreement :) There is currently no License on the code so therefore I would need the maintainers permission

I thank you for your time in helping to drive this forward though

Paul

**Comment by lucazz** [comment]
yep, let's see what @jonmorehouse has to say, then :-)

**Comment by jgillich** [comment]
ping @jonmorehouse

**Comment by matthieudolci** [comment]
ping @jonmorehouse

**Comment by astubbs** [comment]
Ping @jonmorehouse

**Comment by astubbs** [comment]
I prodded him on twitter: https://mobile.twitter.com/jonmorehouse his email address is also public.

**Comment by jonmorehouse** [comment]
Sorry for the late reply to this! I didn't have notifications on for this and just stumbled back upon this repository. 

I've got a rewrite in progress locally, that I wanted to finish up but haven't gotten around too. I should be able to get that done in the next few weeks. As it currently stands, this hasn't been used too much in the last several months so I'm not sure how stable things are. It mainly came out of just a few days of hacking to solve a problem I had at the time.

I'd be happy to move this to core now and follow up with some of my changes over there! I learned quite a bit building this so would also be happy to give any additional feedback on usage etc.

**Comment by matthieudolci** [comment]
@stack72 🎉
@jonmorehouse thank you so much, really looking forward for this

**Comment by stack72** [comment]
Hi @jonmorehouse 

If you are rebuilding the provisioner - maybe opening the PR against the core would be a good thing to do? :) We just added support for provisioner schema within the past month or so

Paul

**Comment by boznius** [comment]
@jonmorehouse any progress on the rewrite or moving this to core , would love to be able to build this against any version of terraform or using it from TF itself.

Thanks for all the great work on this !

**Comment by aus** [comment]
I understand closing the hashicorp/terraform issue, but why close this issue too?

**Comment by falfaro** [comment]
Would the following diff fix the problem of not compiling against Terraform >= 0.7.13?

```
diff --git a/resource_provisioner.go b/resource_provisioner.go
index 6b78ef7..3c9211b 100644
--- a/resource_provisioner.go
+++ b/resource_provisioner.go
@@ -18,6 +18,11 @@ type ResourceProvisioner struct {
        extraVars map[string]string // extra variables that can be passed to the provisioner
 }
 
+func (r *ResourceProvisioner) Stop() error {
+       // Noop for now. TODO in the future.
+       return nil
+}
+
 func (r *ResourceProvisioner) Apply(
        o terraform.UIOutput,
        s *terraform.InstanceState,
```

**Comment by monokal** [comment]
Should we assume this PR is not going to happen then?
