### ISSUE TITLE
Add tags section

### ISSUE THREAD

**Issue by 0xdavidm** [jonmorehouse/terraform-provisioner-ansible#9]
This will be great to see tags section as well as hosts and env vars.

**Comment by jonmorehouse** [comment]
Good ideas!

As it stands, if you add any variables you want to the `--extra-vars` host, it will act as a `host` or `env` variable. It's worth mentioning that each host is provisioned to in isolation using the `ansible-local.py` script.

Also - this should probably be documented more thoroughly!

**Comment by jonmorehouse** [comment]
Just following up from email, it seems like it would be a great option to support adding `tags` as well. Here's some documentation as to how this could work out: http://docs.ansible.com/ansible/playbooks_tags.html

I'd imagine that we'll want to modify the play building component to fetch tasks based upon tags; but let's see how `ansible-playbook` implements it.

**Comment by jonmorehouse** [comment]
Closing, for now in favor of this feature coming in #13
